dependencies {
    api project(':catalog-application')
    api project(':catalog-domain')

    api 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation "net.devh:grpc-client-spring-boot-starter:2.15.0.RELEASE"
    implementation 'com.furnisight:proto-lib:1.0.1782322385582'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'
}
