tasks.withType(JavaCompile) {
    options.compilerArgs += ["-parameters"]
}
dependencies {
    implementation project(':user-application')
    implementation "net.devh:grpc-client-spring-boot-starter:2.15.0.RELEASE"
    implementation 'com.furnisight:proto-lib:1.0.1779346584297'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.flywaydb:flyway-core'
    implementation "org.flywaydb:flyway-database-postgresql"
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    runtimeOnly 'org.postgresql:postgresql'
}
