plugins {
    id 'java-library'
}
tasks.withType(JavaCompile) {
    options.compilerArgs += ["-parameters"]
}
dependencies {
    api project(':user-application')
    api 'org.springframework.boot:spring-boot-starter-web'
    implementation "net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE"
    implementation "net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE"

    implementation 'com.furnisight:proto-lib:1.0.1782520000001'

    api 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation 'org.flywaydb:flyway-core'
    implementation "org.flywaydb:flyway-database-postgresql"
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    runtimeOnly 'org.postgresql:postgresql'
}
