# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1.catalog import catalog_message_pb2 as v1_dot_catalog_dot_catalog__message__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/catalog/catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductSummaries = channel.unary_unary(
                '/v1.catalog.CatalogService/GetProductSummaries',
                request_serializer=v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesRequest.SerializeToString,
                response_deserializer=v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesResponse.FromString,
                _registered_method=True)
        self.GetFavoriteProductSummaries = channel.unary_unary(
                '/v1.catalog.CatalogService/GetFavoriteProductSummaries',
                request_serializer=v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesRequest.SerializeToString,
                response_deserializer=v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesResponse.FromString,
                _registered_method=True)
        self.SearchRecommendedProducts = channel.unary_unary(
                '/v1.catalog.CatalogService/SearchRecommendedProducts',
                request_serializer=v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsRequest.SerializeToString,
                response_deserializer=v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFavoriteProductSummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRecommendedProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductSummaries,
                    request_deserializer=v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesRequest.FromString,
                    response_serializer=v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesResponse.SerializeToString,
            ),
            'GetFavoriteProductSummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFavoriteProductSummaries,
                    request_deserializer=v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesRequest.FromString,
                    response_serializer=v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesResponse.SerializeToString,
            ),
            'SearchRecommendedProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRecommendedProducts,
                    request_deserializer=v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsRequest.FromString,
                    response_serializer=v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.catalog.CatalogService/GetProductSummaries',
            v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesRequest.SerializeToString,
            v1_dot_catalog_dot_catalog__message__pb2.GetProductSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFavoriteProductSummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.catalog.CatalogService/GetFavoriteProductSummaries',
            v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesRequest.SerializeToString,
            v1_dot_catalog_dot_catalog__message__pb2.GetFavoriteProductSummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRecommendedProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.catalog.CatalogService/SearchRecommendedProducts',
            v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsRequest.SerializeToString,
            v1_dot_catalog_dot_catalog__message__pb2.SearchRecommendedProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
