# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/catalog/catalog.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/catalog/catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v1.catalog import catalog_message_pb2 as v1_dot_catalog_dot_catalog__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v1/catalog/catalog.proto\x12\nv1.catalog\x1a v1/catalog/catalog_message.proto2\xf2\x02\n\x0e\x43\x61talogService\x12\x66\n\x13GetProductSummaries\x12&.v1.catalog.GetProductSummariesRequest\x1a\'.v1.catalog.GetProductSummariesResponse\x12~\n\x1bGetFavoriteProductSummaries\x12..v1.catalog.GetFavoriteProductSummariesRequest\x1a/.v1.catalog.GetFavoriteProductSummariesResponse\x12x\n\x19SearchRecommendedProducts\x12,.v1.catalog.SearchRecommendedProductsRequest\x1a-.v1.catalog.SearchRecommendedProductsResponseB\x1a\n\x16\x63om.furnisight.catalogP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.catalog.catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.furnisight.catalogP\001'
  _globals['_CATALOGSERVICE']._serialized_start=75
  _globals['_CATALOGSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
