plugins {
    id 'java-library'
}

dependencies {
    api project(':promotion-application')
    api project(':promotion-domain')

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api "net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE"
    implementation "net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE"
    api 'com.furnisight:proto-lib:1.0.1782210916252'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.security:spring-security-test'
}
