services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
