plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':review-adapter')
    implementation project(':review-application')
    implementation project(':review-domain')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
