plugins {
    id 'io.spring.dependency-management'
}
tasks.withType(JavaCompile) {
    options.compilerArgs += ["-parameters"]
}
dependencies {
    implementation project(':user-application')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.security:spring-security-test'
}
