CREATE TABLE orders (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    status VARCHAR(50) NOT NULL,
    sub_total DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    shipping_fee DOUBLE PRECISION,
    shipping_discount DOUBLE PRECISION,
    discount_amount DOUBLE PRECISION,
    insurance_fee DOUBLE PRECISION,
    saved_amount DOUBLE PRECISION,
    shipping_address_name VARCHAR(255),
    shipping_address_phone VARCHAR(50),
    shipping_address_detail TEXT,
    shipping_method VARCHAR(100),
    customer_note TEXT,
    payment_method VARCHAR(50),
    payment_status VARCHAR(50),
    paid_amount DOUBLE PRECISION,
    paid_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE order_items (
    id UUID PRIMARY KEY,
    order_id UUID NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    variant_id VARCHAR(50),
    category_name VARCHAR(100),
    product_name VARCHAR(255) NOT NULL,
    variant_description VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    old_price DOUBLE PRECISION,
    quantity INTEGER NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
