plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.furnisight'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenLocal()
	mavenCentral()
	maven {
		url = uri("https://maven.pkg.github.com/minhhien-e/furnisight-backend")
		credentials {
			username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("GITHUB_ACTOR")
			password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("GITHUB_TOKEN")
		}
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'

	implementation "net.devh:grpc-client-spring-boot-starter:2.15.0.RELEASE"
	implementation "net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE"
	implementation 'com.furnisight:proto-lib:1.0.1781077383461'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
