apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-review-sentiment-env
  namespace: furnisight-apps
data:
  # --- CẤU HÌNH HỆ THỐNG (SYSTEM) ---
  AI_REVIEW_SENTIMENT_GRPC_PORT: "9090"

  # --- DATABASE ---
  MONGO_HOST: mongo.furnisight-infras.svc.cluster.local
  POSTGRES_HOST: postgres.furnisight-infras.svc.cluster.local

  # --- HẠ TẦNG (KAFKA, REDIS, CACHE...) ---

  # --- KẾT NỐI GRPC (GRPC CLIENTS) ---
  REVIEW_SERVICE_GRPC_HOST: review-service

  # --- CẤU HÌNH KHÁC (OTHERS) ---
  CLOUDINARY_FOLDER: furnisight/ai-reconstruction
  RETAIN_LOCAL_OUTPUTS: "false"
  STORAGE_BACKEND: cloudinary

