apiVersion: v1
data:
  # --- CẤU HÌNH HỆ THỐNG (SYSTEM) ---

  # --- DATABASE ---
  DB_URL: jdbc:postgresql://postgres.furnisight-infras.svc.cluster.local:5432/furnisight_catalog_db
  DB_USERNAME: postgres

  # --- HẠ TẦNG (KAFKA, REDIS, CACHE...) ---

  # --- CẤU HÌNH KHÁC (OTHERS) ---

kind: ConfigMap
metadata:
  name: catalog-service-env
  namespace: furnisight-apps
