apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: furnisight-frontend
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Caching cho các file tĩnh (CSS, JS, Hình ảnh)
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 6M;
            access_log off;
            add_header Cache-Control "public, max-age=15552000, immutable";
        }
    }
