apiVersion: v1
data:
  # --- CẤU HÌNH HỆ THỐNG (SYSTEM) ---

  # --- DATABASE ---
  DB_URL: jdbc:postgresql://postgres.furnisight-infras.svc.cluster.local:5432/furnisight_message_db
  DB_USERNAME: postgres

  # --- HẠ TẦNG (KAFKA, REDIS, CACHE...) ---
  KAFKA_CONSUMER_GROUP_ID: message-service-group
  REDIS_PORT: "6379"

kind: ConfigMap
metadata:
  name: message-service-env
  namespace: furnisight-apps
