apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-env
  namespace: furnisight-apps
data:
  # --- CẤU HÌNH HỆ THỐNG (SYSTEM) ---
  JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
  SERVER_PORT: "8080"
  GRPC_SERVER_PORT: "9090"
  TZ: Asia/Ho_Chi_Minh

  # --- HẠ TẦNG (KAFKA, REDIS, CACHE...) ---
  KAFKA_BOOTSTRAP_SERVERS: "kafka.furnisight-infras.svc.cluster.local:29092"
  KAFKA_HOST: "kafka.furnisight-infras.svc.cluster.local"
  KAFKA_PORT: "29092"
  REDIS_HOST: "redis.furnisight-infras.svc.cluster.local"
  TRANSLATION_BASE_URL: "http://libretranslate.furnisight-infras.svc.cluster.local:5000"

  # --- KẾT NỐI GRPC (GRPC CLIENTS) ---
  AI_REVIEW_SENTIMENT_GRPC_ADDRESS: "static://ai-review-sentiment.furnisight-apps.svc.cluster.local:9090"

  CATALOG_SERVICE_GRPC_ADDRESS: "static://catalog-service.furnisight-apps.svc.cluster.local:9090"
  MEDIA_SERVICE_GRPC_ADDRESS: "static://media-service.furnisight-apps.svc.cluster.local:9090"
  MESSAGE_SERVICE_GRPC_ADDRESS: "static://message-service.furnisight-apps.svc.cluster.local:9090"
  ORDER_SERVICE_GRPC_ADDRESS: "static://order-service.furnisight-apps.svc.cluster.local:9090"
  PROMOTION_SERVICE_GRPC_ADDRESS: "static://promotion-service.furnisight-apps.svc.cluster.local:9090"
  REVIEW_SERVICE_GRPC_ADDRESS: "static://review-service.furnisight-apps.svc.cluster.local:9090"
  USER_SERVICE_GRPC_ADDRESS: "static://user-service.furnisight-apps.svc.cluster.local:9090"
