server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  reactor:
    context-propagation: auto
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL}/.well-known/jwks.json
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/users/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                - name: RewritePath
                  args:
                    regexp: /users/(?<segment>.*)
                    replacement: /api/v1/$\{segment}

            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL}
              predicates:
                - Path=/catalog/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /catalog/(?<segment>.*)
                    replacement: /api/v1/$\{segment}

            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URL}
              predicates:
                - Path=/notifications/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /notifications/(?<segment>.*)
                    replacement: /api/v1/$\{segment}

            - id: ai-image-classifier
              uri: ${AI_IMAGE_CLASSIFIER_URL}
              predicates:
                - Path=/ai-classifier/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /ai-classifier/(?<segment>.*)
                    replacement: /$\{segment}

            - id: media-service-api
              uri: ${MEDIA_SERVICE_URL}
              predicates:
                - Path=/media/**
              filters:
                - name: RewritePath
                  args:
                    regexp: /media/(?<segment>.*)
                    replacement: /api/v1/$\{segment}

          forwarded:
            enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
app:
  security:
    whitelist:
      public-all: ${APP_SECURITY_WHITELIST_PUBLIC_ALL}
      auth-all: ${APP_SECURITY_WHITELIST_AUTH_ALL}
      password-all: ${APP_SECURITY_WHITELIST_PASSWORD_ALL}
      oauth-all: ${APP_SECURITY_WHITELIST_OAUTH_ALL}
      public-get: ${APP_SECURITY_WHITELIST_PUBLIC_GET}
