server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  reactor:
    context-propagation: auto
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL}/.well-known/jwks.json
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5 # 5 request / giây
                redis-rate-limiter.burstCapacity: 10 # tối đa burst
            - name: RewritePath
              args:
                regexp: /users/(?<segment>.*)
                replacement: /api/v1/$\{segment}

        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL}
          predicates:
            - Path=/catalog/**
          filters:
            - name: RewritePath
              args:
                regexp: /catalog/(?<segment>.*)
                replacement: /api/v1/$\{segment}
      forwarded:
        enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
logging:
  level:
    # Gateway core
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.route: DEBUG

    # RateLimiter
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

    # Security (QUAN TRỌNG NHẤT)
    org.springframework.security.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.web.server: TRACE
    org.springframework.security.web.server.authorization: TRACE
    org.springframework.security.web.server.authorization.AuthorizationWebFilter: TRACE
    org.springframework.security.web.server.csrf: TRACE
    org.springframework.security.web.server.util.matcher: TRACE

    # WebFlux / Reactor
    org.springframework.web.server: DEBUG
    reactor.netty: DEBUG
app:
  security:
    auth-whitelist: ${AUTH_WHITELIST}
