plugins {
    id 'java-library'
}

dependencies {
    implementation project(":media-core")
    // JPA
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    // Flyway
    api 'org.flywaydb:flyway-core'
    api 'org.flywaydb:flyway-database-postgresql'
    // Redis
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    // Mime type
    implementation 'org.apache.tika:tika-core:2.9.0'
    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'
}
