apiVersion: v1
kind: Namespace
metadata:
  name: furnisight-infras
---
apiVersion: v1
kind: Namespace
metadata:
  name: furnisight-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: furnisight-frontend
