package com.furnisight.catalog.domain.exceptions.enums;

public enum ErrorCode {
    INSUFFICIENT_STOCK,
    INVALID_PRODUCT_STATE,
    PRODUCT_NOT_FOUND,
    PRODUCT_OWNERSHIP_DENIED,
    INVALID_PRODUCT_DIMENSIONS,
    INVALID_PRODUCT_DESCRIPTION,
    INVALID_PRODUCT_NAME,
    INVALID_SKU,
    INVALID_PRICE,
    INVALID_STOCK_QUANTITY,
    MISSING_PRODUCT_VARIANT,
    OUTBOX_EVENT_PROCESSING_FAILED,
    CATEGORY_NOT_FOUND,
    DUPLICATE_CATEGORY_SLUG,
    INVALID_CATEGORY_NAME,
    INVALID_CATEGORY_SLUG,
    DUPLICATE_CATEGORY_NAME
}
