apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: furnisight-infras
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: furnisight-infras
data:
  postgresql.conf: |
    max_connections = 1000
    shared_buffers = 512MB
    effective_cache_size = 1536MB
    work_mem = 4MB
    maintenance_work_mem = 128MB
    min_wal_size = 1GB
    max_wal_size = 2GB
    listen_addresses = '*'
    log_timezone = 'Asia/Ho_Chi_Minh'
    datestyle = 'iso, mdy'
    timezone = 'Asia/Ho_Chi_Minh'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: furnisight-infras
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres # In prod, read from secret
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: PGTZ
              value: Asia/Ho_Chi_Minh
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script
          configMap:
            name: postgres-init-script
        - name: postgres-config
          configMap:
            name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: furnisight-infras
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
