plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':user-presentation')
    implementation project(':user-infrastructure')
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
