plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.furnisight'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        url = uri("https://maven.pkg.github.com/minhhien-e/furnisight-backend")
        credentials {
            username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("GITHUB_ACTOR")
            password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("GITHUB_TOKEN")
        }
    }
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // gRPC
    implementation "net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE"
    implementation 'com.furnisight:proto-lib:1.0.1782210916252'

    // Database
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // Cloudinary
    implementation 'com.cloudinary:cloudinary-http45:1.39.0'

    // Tika for MIME detection
    implementation 'org.apache.tika:tika-core:2.9.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Dotenv
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
