plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':order-adapter')
    implementation project(':order-application')
    implementation project(':order-domain')
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}
