syntax = "proto3";

package v1.catalog;

option java_multiple_files = true;
option java_package = "com.furnisight.catalog";

message GetProductSummariesRequest {
  repeated GetProductSummaryItem items = 1;
  repeated string product_ids = 2 [deprecated = true];
}

message GetProductSummariesResponse {
  repeated ProductSummary products = 1;
}

message GetProductSummaryItem {
  string product_id = 1;
  string selected_variant_id = 2;
}

message ProductSummary {
  string id = 1;
  string slug = 2;
  string name = 3;
  string image = 4;
  ProductSummaryVariant variant = 5;
  string selected_variant_id = 6;
  repeated ProductSummaryVariant variants = 7;
}

message ProductSummaryVariant {
  string id = 1;
  optional double price = 2;
  optional double old_price = 3;
  optional int32 stock_quantity = 4;
  optional double length = 5;
  optional double width = 6;
  optional double height = 7;
  optional double weight = 8;
  string color = 9;
  string material = 10;
  string warranty = 11;
}
