# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/ai/review_sentiment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'v1/ai/review_sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cv1/ai/review_sentiment.proto\x12\x05v1.ai\"-\n\x1d\x41nalyzeReviewSentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"G\n\x1e\x41nalyzeReviewSentimentResponse\x12\x11\n\tsentiment\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x32\x7f\n\x16ReviewSentimentService\x12\x65\n\x16\x41nalyzeReviewSentiment\x12$.v1.ai.AnalyzeReviewSentimentRequest\x1a%.v1.ai.AnalyzeReviewSentimentResponseB\x1c\n\x18\x63om.furnisight.ai.reviewP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.ai.review_sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.furnisight.ai.reviewP\001'
  _globals['_ANALYZEREVIEWSENTIMENTREQUEST']._serialized_start=39
  _globals['_ANALYZEREVIEWSENTIMENTREQUEST']._serialized_end=84
  _globals['_ANALYZEREVIEWSENTIMENTRESPONSE']._serialized_start=86
  _globals['_ANALYZEREVIEWSENTIMENTRESPONSE']._serialized_end=157
  _globals['_REVIEWSENTIMENTSERVICE']._serialized_start=159
  _globals['_REVIEWSENTIMENTSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
