# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from v1.ai import review_sentiment_pb2 as v1_dot_ai_dot_review__sentiment__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/ai/review_sentiment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewSentimentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeReviewSentiment = channel.unary_unary(
                '/v1.ai.ReviewSentimentService/AnalyzeReviewSentiment',
                request_serializer=v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentRequest.SerializeToString,
                response_deserializer=v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentResponse.FromString,
                _registered_method=True)


class ReviewSentimentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeReviewSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewSentimentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeReviewSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeReviewSentiment,
                    request_deserializer=v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentRequest.FromString,
                    response_serializer=v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ai.ReviewSentimentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.ai.ReviewSentimentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewSentimentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeReviewSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ai.ReviewSentimentService/AnalyzeReviewSentiment',
            v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentRequest.SerializeToString,
            v1_dot_ai_dot_review__sentiment__pb2.AnalyzeReviewSentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
