plugins {
    id 'java'
}
tasks.withType(JavaCompile) {
    options.compilerArgs += ["-parameters"]
}
tasks.named('test') {
    useJUnitPlatform()
}
dependencies {
    implementation project(':catalog-infrastructure')
    implementation "net.devh:grpc-client-spring-boot-starter:2.15.0.RELEASE"
    implementation "net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE"
    implementation 'com.furnisight:proto-lib:1.0.1782520000001'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
