plugins {
    id 'java-library'
}
dependencies {
    api project(':notification-application')
    api project(':notification-domain')

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    implementation "net.devh:grpc-client-spring-boot-starter:2.15.0.RELEASE"
    implementation "net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE"
    implementation 'com.furnisight:proto-lib:1.0.1779360197693'
    api 'org.springframework.kafka:spring-kafka'
    api 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.springframework.security:spring-security-test'
}
