plugins {
    id 'java-library'
    id 'nu.studer.jooq' version '9.0'
}

dependencies {
    api project(':review-core')
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.flywaydb:flyway-core'
    api 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    jooqGenerator 'org.postgresql:postgresql'
    runtimeOnly 'org.postgresql:postgresql'
    api 'org.springframework.kafka:spring-kafka'
}

jooq {
    configurations {
        main {
            generationTool {
                logging = org.jooq.meta.jaxb.Logging.WARN
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = System.getenv("JOOQ_DB_URL") ?: 'jdbc:postgresql://localhost:5433/furnisight_review_db'
                    user = System.getenv("JOOQ_DB_USER") ?: 'postgres'
                    password = System.getenv("JOOQ_DB_PASSWORD") ?: 'postgres'
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = 'public'
                        includes = 'reviews'
                    }
                    generate {
                        deprecationOnUnknownTypes = false
                    }
                    target {
                        packageName = 'com.furnisight.review.infrastructure.database.repository.jooq'
                        directory = 'build/generated-sources/jooq'
                    }
                }
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs += 'build/generated-sources/jooq/main'
        }
    }
}
tasks.named('compileJava') {
    dependsOn tasks.named('generateJooq')
}

clean {
    delete "build/generated-sources/querydsl"
}

