server:
  port: 8080
  servlet:
    context-path: /api/v1

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9094}
  client:
    catalog-service:
      address: ${CATALOG_GRPC_ADDRESS:static://localhost:9093}
      negotiationType: plaintext

spring:
  application:
    name: cart-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/furnisight_cart}
      uuid-representation: standard


