apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: furnisight-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: cart-service
        image: furnisight-cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: shared-env
        - configMapRef:
            name: cart-service-env
        - secretRef:
            name: furnisight-secrets
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: furnisight-apps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 9090
    targetPort: 9090
  selector:
    app: cart-service
